# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be236b8ffb53e8518a6864528a19873ae942d6d0ff34f36c532fa50b730fef11f697c09dcef3281dc00a391595449b32ae122f822a8e506261a79371869f13fc

test:
  secret_key_base: 58230c533257a25cdfe4930c363fc128721a8248aa65b13e12f1a133382a976f367577284de25558729bad3247df8bfc9dbf96261517ba3cf5a72638e79f5489

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
